#' View the content of an antares output
#'
#' This function displays each element of an \code{antaresOutput} object in a
#' spreadsheet-like viewer
#'
#' @param x
#' An object of class \code{antaresOutput}, generated by the function
#' \code{\link{importOutput}}.
#'
#' @return
#' Invisible NULL.
#'
viewAntares <- function(x) {
  if (!is(x, "antaresOutput")) stop("Argument is not an antaresOutput object.")

  for (k in names(x)) {
    if (is.data.frame(x[[k]])) View(x[[k]], k)
  }

  invisible(NULL)
}
