#' View the content of an antares output
#'
#' This function displays each element of an \code{antaresData} object in a
#' spreadsheet-like viewer
#'
#' @param x
#' An object of class \code{antaresData}, generated by the function
#' \code{\link{readAntares}}.
#' @param ...
#' Currently unused
#'
#' @return
#' Invisible NULL.
#' 
#' @examples 
#' \dontrun{
#' setSimulationPath()
#' 
#' nodes <-readAntares()
#' viewAntares(nodes)
#' 
#' output <- studyAntares(nodes="all", links = "all", clusters = "all")
#' viewAntares(output) # Opens three data viewers for each element of output
#' }
#' 
#' @export
#'
#'
viewAntares <- function(x, ...) {
  UseMethod("viewAntares", x)
}

#' @export
viewAntares.default <- function(x, ...) {
  title <- deparse(substitute(x))
  View(x, title)
}

#' @export
viewAntares.antaresDataList <- function(x, ...) {
  title <- deparse(substitute(x))
  for (k in names(x)) {
    if (is.data.frame(x[[k]])) View(x[[k]], paste(title, k, sep = "$"))
  }

  invisible(NULL)
}
