#' View the content of an antares output
#'
#' This function displays each element of an \code{antaresTable} object in a
#' spreadsheet-like viewer
#'
#' @param x
#' An object of class \code{antaresTable}, generated by the function
#' \code{\link{readAntares}}.
#'
#' @return
#' Invisible NULL.
#'
#'
#' @export
#'
viewAntares <- function(x) {
  if (!is(x, "antaresTable")) stop("Argument is not an antaresTable object.")

  for (k in names(x)) {
    if (is.data.frame(x[[k]])) View(x[[k]], k)
  }

  invisible(NULL)
}
